### PR TITLE
Use unlogged tables for test suite

### PR DESCRIPTION
**Pull request by andyatkinson**
https://twitter.com/andatki/status/1715213122292551706

I tried repeated runs with this enabled and disabled, and didn't
see a significant change.

Seems like there's no downside to enabling it though so I will
enable unlogged tables for the test environment.

Finished in 1.753649s, 20.5286 runs/s, 61.0156 assertions/s.
Finished in 1.810954s, 19.8790 runs/s, 59.0849 assertions/s.
Finished in 1.772443s, 20.3109 runs/s, 60.3687 assertions/s.

Finished in 1.823601s, 19.7412 runs/s, 58.6751 assertions/s.
Finished in 1.826130s, 19.7138 runs/s, 58.5939 assertions/s.
Finished in 1.749217s, 20.5806 runs/s, 61.1702 assertions/s.

### CODE REVIEW

**Comment by andyatkinson** [comment]
Looks like `users` table in a test is not actually an unlogged table.

Does this work for the SQL formatted structure file dump (db/structure.sql)? 

```
[23] pry(#<DriverTest>)> ActiveRecord::Base.connection.execute("select current_database()").map{|r| puts r}
{"current_database"=>"rideshare_test"}

[21] pry(#<DriverTest>)> ActiveRecord::Base.connection.execute("select relpersistence, relname from pg_class where relname = 'users'").map{|r| puts r }
{"relpersistence"=>"p", "relname"=>"users"}

 u is unlogged, but it's p
```
https://stackoverflow.com/a/29900169/126688

https://guides.rubyonrails.org/configuring.html#activerecord-connectionadapters-postgresqladapter-create-unlogged-tables

**Comment by andyatkinson** [comment]
https://twitter.com/andatki/status/1741323444208230871


cc @fatkodima

**Comment by fatkodima** [comment]
I checked yours Rails version - this should work. Both with `schema.db` and `structure.sql` doesn't matter, because the schema us dumped only for `development` environment, but unlogged tables are configured for `test`, that's why you don't see `"UNLOGGED"` in these files.

Yeah, you don't see an improvement, because the tests are run in under 2s and the improvement can be so small that it falls within error. We have a significant amount of tests with lots of write queries in them and there we see a lot of improvements.

**Comment by andyatkinson** [comment]
Thanks for taking a look @fatkodima! 

I was less concerned about performance benefits, and more concerned that the test env tables were created as expected (relpersistence=u). Here's what I saw:

- Using db/structure.sql, which is dumped from dev, which has all normal "logged" tables
- added the setting and recreated the tables (db:reset)
- Now we're expecting the test env tables to be unlogged. For me when I used a debugger and checked the table type in PostgreSQL from within a running test, and I saw relpersistence=p (logged) for the table, meaning they were not created as unlogged tables. 

Is there a unit test that asserts relpersistence=u for the postgresql adapter, where both dump formats are used?

My theory was the "unlogged" keyword was getting passed in only for the Ruby schema dump format, which has a "dynamic" creation method, vs. the SQL format which uses the "create table"
statements "as is" from the dump file.

I'd need to look in Active Record for how the tables are created from db:test:prepare when the app is configured with the SQL schema dump format.

Thanks for the help!

**Comment by fatkodima** [comment]
> My theory was the "unlogged" keyword was getting passed in only for the Ruby schema dump format

Why not to check the sources? https://github.com/rails/rails/pull/34221

Are you connected to the correct (test) database? I got `relpersistence='u'` and `Unlogged table "public.users"` in the psql.

If still not, can you describe the exact steps you did in the app for this feature to work?

**Comment by andyatkinson** [comment]
Thanks again @fatkodima for checking this out. The nudge helped me get the motivation to keep digging into this.

The problem was not with Active Record but was with my app and DB configuration. I can happily confirm that the unlogged tables are supported regardless of whether the schema dump format is Ruby or SQL.

If you're curious what changed here, I made a few changes which are documented in this commit message:

https://github.com/andyatkinson/rideshare/pull/125/commits/43a00ed625e59e7424f59e099f5056f02f2b79c3

Some quirks in this app are:
* Using a app-specific (non public) schema for Rideshare (called “rideshare”), which is now used for both dev and test DBs, and was previously used only in dev
* Making sure the PostgreSQL user is configured with access to the rideshare schema, including for the separated test DB user

With that in place, running `bin/rails db:migrate` on the test environment generates the tables with the `UNLOGGED` keyword populated as documented, which is pretty cool. I'm then able to connect from psql to the DB and run `\d <tablename>` to confirm it's an unlogged table (or check `relpersistence` as shown originally).

All working!

**Pull request merged**
